package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	QUIT, CONFIRM_QUIT,
	TOKEN_REQUEST, TOKEN_SEND,
	PUT_UNLOCK,
	PING, PONG, SUS_ASK, SUS_PING, SUS_PONG, UPDATE_AFTER_DEATH, ASK_HAS_TOKEN, TELL_HAS_TOKEN,
	FOLLOW_REQ, FOLLOW_ACC, REMOVE_FILE, REMOVE_FILE_UNLOCK,
	REMOVE_FROM_BACKUP, BACKUP,

}
